### ISSUE TITLE
Support for GitHub Actions

### ISSUE THREAD

**Issue by rlove** [AnyStatus/AnyStatus#14]
It would be nice to monitor specific GitHub workflows/actions that are triggered on a specified GitHub repository.

**Comment by AlonAm** [comment]
Depends on #24

**Comment by AlonAm** [comment]
A new widget that shows the status of a GitHub Workflow is now available in v3.1 on Microsoft Store.
To use the widget, you'll need to create a GitHub Endpoint first, then create the widget, and select the endpoint in the widget.
In addition to the workflow status, I've added widgets for GitHub Pages Build Status, and GitHub Issues List.
These are currently in preview, any feedback would be appreciated.
Hope you find it useful.
Enjoy

**Comment by AlonAm** [comment]
@rlove done.
