### ISSUE TITLE
Custom notifications

### ISSUE THREAD

**Issue by dotMorten** [AnyStatus/AnyStatus#15]
I've been trying to use the TextLabelWidget and make a notification when its text label changes. So far it appears the only thing that can make a notification is Status changed. I tried extending the `INotification` and `NotificationHandler` types, but it appears the stuff to actually send the notification is only in the actual app (where the `StatusChangedNotificationHandler` is defined), so the types to do this are not available. It would be nice if widges could create custom notifications based on custom logic, and not just be limited to `Status`.
Especially for TextLabelWidget, I'd like to be notified when its value changes.

**Comment by AlonAm** [comment]
How about we add some interface to the API that you can inject into handlers like INotificationService (or Sender?)
You'll then be able to do something like _service.Send(new Notification(...))

**Comment by AlonAm** [comment]
Similar concept as in IDialogService

**Comment by AlonAm** [comment]
Added [INotificationService](https://github.com/AnyStatus/AnyStatus/blob/main/src/Core/AnyStatus.API/Notifications/INotificationService.cs) which you can call from any plug-in. Let me know what you think.

**Comment by AlonAm** [comment]
@dotMorten ok to close?

**Comment by dotMorten** [comment]
Haven't been able to make it work so far.
Any chance you could modify either the sample plugin, or change the nuget plugin to raise a notification that the version changed, so I have something to work off / learn from ?

**Comment by AlonAm** [comment]
Oh, sorry about that. I tested it using one of the plugins without commiting the test changes. Let me check that again

**Comment by AlonAm** [comment]
Here's a quick demo for sending notifications from a widget handler
https://github.com/AnyStatus/AnyStatus/blob/main/src/Plugins/AnyStatus.Plugins/Demo/DemoNotificationsWidget.cs

If you don't get notifications on your desktop, please make sure your Windows 10 focus assistant is turned off in the action center.
I'm continuously looking for ways to make the API self-explanatory or at least easy to use. Your feedback is most welcomed.
Are you satisfied with the INotificationService interface?
Would you prefer using MediatR instead? For example ```mediator.Send(new DesktopNotification())```
Also, in v2 there's a feature called Triggers that enables you to trigger custom actions on specific status changes. Actions include showing a custom notification or starting a new process. Would you prefer that feature over the INotificationService interface?
Thanks for the feedback

**Comment by dotMorten** [comment]
Thanks. I just got it working too! https://github.com/AnyStatus/AnyStatus/commit/b53737ad4b7db259675ae7544a3216a5dc08b101

**Comment by dotMorten** [comment]
Triggers are interesting. For monitoring my home assistant sensors, I could see being able to trigger a notification when a value drops below of above something, or if a value changes, rather than building it all into each widget.

**Comment by AlonAm** [comment]
I suggest adding the threshold limits to the widget as properties with default values so you can change them later
