### ISSUE TITLE
Feature: Summarize a group's member states in the group

### ISSUE THREAD

**Issue by somewhatabstract** [AnyStatus/AnyStatus#16]
### Installed product versions
- Visual Studio: 2015 Enterprise Update 3
- AnyStatus: (about box says 1.0, but I think it's 0.8)
### Description

With things grouped, I want to collapse the groups and see a summary of their contents. Perhaps a percentage of failures within the group or percentage of passes.
### Steps to recreate
1. Have a group
2. Add two or more items with different pass/fail states
3. Collapse the group
### Current behavior

You cannot tell if anything inside the group is passed or failed without expanding it
### Expected behavior

You can tell if something inside the group is failing or if they all pass, and possibly even know how many (like all, or just 50%).

Also would be useful to summarise all monitors since the list could be quite long. Perhaps some sort of summary always visible header.

**Comment by AlonAm** [comment]
great idea, i was thinking about it too.
I'll share my thoughts soon (just got back to work from a vacation)

**Comment by AlonAm** [comment]
in another build monitor I developed a few years ago, what I did was
-the group color is green when all items within it are Ok, including nested groups.
-the group color is red when one or more items within it has failed.
-other status codes have higher priority. for example, when a build is running the group color is blue. when the build completes, the color is changed back to green/red.

**Comment by somewhatabstract** [comment]
That seems pretty fair to me as a starting point. Obviously, it should support symbols when that stuff gets done. We might want the ability to summarize categories (like 4 fail, 5 pass, 1 pending) in some way, but that's certainly not MVP.

**Comment by AlonAm** [comment]
Textual and/or icon summary should be somehow minimal.

It can be numeric like: [5/1]
or we can mention just the number of failures: "1 failed"

We'll try different variations once the monitor State is added

**Comment by AlonAm** [comment]
added a colored status indicator to folders that indicates the status of its members
i'll test it for a while before releasing to VS Gallery

CI build can be downloaded from http://vsixgallery.com/extension/AnyStatus.VSPackage.6f25620d-ff50-42d1-89da-709a45cebe10/

let me know what you think

**Comment by AlonAm** [comment]
here's the state enum (ordered by priority):
https://github.com/AlonAm/AnyStatus/blob/master/src/AnyStatus/Features/HealthChecks/ItemState.cs

here's the mapping between state and color (this brings us closer to enabling color customization):
https://github.com/AlonAm/AnyStatus/blob/master/src/AnyStatus/Features/ToolWindow/StateToBrushConverter.cs

**Comment by somewhatabstract** [comment]
I just tried it out. It's definitely better. The aggregate info we discussed in #17 will make it even better, but as it stands, this is a great improvement. I can leave the groups collapsed and see that there's an issue to look deeper. Good stuff.

**Comment by AlonAm** [comment]
colored status indicator for folders released in 0.9.6

**Comment by AlonAm** [comment]
let me know if you are experiencing any issues with the new feature.
it is expected to support all use cases, for example, when all folders are collapsed the color should change when the status of an element within it has changed.
the same when adding or deleting items or when moving items between folders.

**Comment by AlonAm** [comment]
Also, I'v changed the colors a bit so when an item has an Error (for example, one of the properties is incorrect) the status color will be Dark Red.
While an item is failing (e.g., build failed) the color will be Red.

**Comment by AlonAm** [comment]
This issue was moved to AnyStatus/Support#8
