### ISSUE TITLE
maximized window cant be moved or resized

### ISSUE THREAD

**Issue by kami-soft** [AnyStatus/AnyStatus#2]
steps to reproduce:  
1. push left mouse button on window header
2. drag to top of screen (one of standart Windows action for maximize window).

Maximized window cant be moved or resized: double click on header (standart action for restore size), drag window header, trying to resize... nothing works.  
I found only one solution: click "Open" menu item from tray icon

**Comment by AlonAm** [comment]
The issue has been fixed in the latest version
