### ISSUE TITLE
Improve endpoint experience

### ISSUE THREAD

**Issue by dotMorten** [AnyStatus/AnyStatus#21]
When using a widget that requires an endpoint, the first experience you get is no way to pick an endpoint, and no obvious way to add one. It took me a while to realize there's a different spot to go add these.
It would be nice if the dropdown had an option at the bottom that says "add new endpoint..." and take you to the endpoint page with the right type pre-selected (or filtered to compatible ones)), and then navigate back once done.

Second I'd like to see the dropdown filtered by compatible endpoints, rather than showing all endpoints. Ie I should only see the nugets endpoint for the nuget widgets.

**Comment by dotMorten** [comment]
That was fast!

**Comment by AlonAm** [comment]
The second request was easy but the first one may take a little longer since the input control is rendered on the fly. I may need to replace that with a custom control dedicated to endpoints instead of the EndpointSource attribute

**Comment by AlonAm** [comment]
So far I was able to add a "Manage Endpoints" link that opens the Endpoints page
But the user experience isn't ideal, still trying to figure it out

![image](https://user-images.githubusercontent.com/3127610/116214500-6e512a00-a74f-11eb-9c20-d36b249719a7.png)

**Comment by AlonAm** [comment]
@dotMorten done and released to Microsoft Store in build 3.0.390.0
Not the ideal UI but good enough for now

**Comment by dotMorten** [comment]
@AlonAm Looks great! I think it's fine. Much improved user experience.
