### ISSUE TITLE
Feature: slightly better Appveyor setup

### ISSUE THREAD

**Issue by scottfavre** [AnyStatus/AnyStatus#24]
AnyStatus 0.9.17

The current window for setting up an Appveryor integration is pretty good (I like the example URL to describe what the slug is).

![image](https://cloud.githubusercontent.com/assets/150353/20215882/64520bbe-a7e5-11e6-9517-c1bc95d4fbff.png)

However, since the account name and slug are both in the URL, why not just have an entry for the project URL and parse out the account name and slug from that, since it is a well-known format?

**Comment by AlonAm** [comment]
That's what I did with Jenkins and you're right it's easier to just paste the URL

**Comment by AlonAm** [comment]
I have implemented the change but haven't decided yet whether to push it or not.
From a technical perspective it is more convenient and efficient to have two separate properties instead of one (URL) when using multiple AppVeyor APIs because the URL has to be parsed on every operation.

**Comment by AlonAm** [comment]
This issue was moved to AnyStatus/Support#10
