### ISSUE TITLE
Feature: Option to change interval for items under a folder

### ISSUE THREAD

**Issue by modulexcite** [AnyStatus/AnyStatus#29]
### Installed product versions
- Visual Studio: 2015 Professional
- AnyStatus: v0.10.38

### Description
Add an option to change interval for anything grouped under a folder.

### Steps to recreate
N/A

### Current behavior
There is no such option currently.

### Expected behavior
Change the time interval for every item configured under a folder.

**Comment by AlonAm** [comment]
could you please describe how you expect that feature to appear on the UI?
should it be a modal dialog or a sub-context-menu with predefined values, etc.

**Comment by modulexcite** [comment]
My personal preference is to go with a modal dialog but I'm not sure how others feel about that.

**Comment by AlonAm** [comment]
This issue was moved to AnyStatus/Support#7
