### ISSUE TITLE
"Unauthorised" message using azure devops.

### ISSUE THREAD

**Issue by finlaybob** [AnyStatus/AnyStatus#40]
I cannot seem to connect Azure Devops widget. There is not a lot of info on how to set this up - i.e. what URL exactly is required?. 

Also there is not a lot of detail in the exception 😅

Is there some setting that I need to have changed on the Azure Devops perhaps? 
(I have created an access token with full access to test this, and it still says Unauthorised)

![image](https://user-images.githubusercontent.com/2033345/128005537-fc3e7eb9-4fdc-4cf5-8f8a-75f886d61f6f.png)

**Comment by AlonAm** [comment]
Make sure the token has access to all organizations

**Comment by finlaybob** [comment]
I've also tried this on a personal instance of Azure Devops that I am the full owner of and have full permissions for and I am getting the following:

![image](https://user-images.githubusercontent.com/2033345/128215420-958ed4e5-a736-495a-84cd-038d18cfbd03.png)

**Comment by AlonAm** [comment]
Make sure the personal access token includes all scopes you want to be able to monitor

**Comment by finlaybob** [comment]
It's not the server version. 
I've ouble checked and in both cases I have given full access. 
![image](https://user-images.githubusercontent.com/2033345/128228178-10efb7bf-e7c0-416e-8b31-ab7dac5f7653.png)

I've got the repo forked so I may have a quick look and debug. 

Any ideas what else it could be?

**Comment by AlonAm** [comment]
The API response may provide more details

**Comment by AlonAm** [comment]
Azure DevOps = the cloud hosted version
Azure DevOps Server = the one you can install on your own

**Comment by finlaybob** [comment]
So for the first requests when I set the endpoint are working. I can get a list of 'accounts'

However when I select an account and debug - the response URL is shown as

`https://dev.azure.com/finlaybob/finlaybob/_apis/projects?api-version=5.1`

As you can see the org is listed twice. Unsurprising it returns a 404!!

**Comment by finlaybob** [comment]
Thanks for the help! Closing issue!

**Comment by AlonAm** [comment]
Added a little info icon to help users understand this,
any help to improve this information would be very appreciated
![image](https://user-images.githubusercontent.com/3127610/128410591-e22c6810-eab7-425a-a13f-25031be07db4.png)

**Comment by finlaybob** [comment]
That is super helpful as I made that mistake first. 

Well, that and I put in the wrong URL for the address 🤐

Perhaps a similar thing for address, saying something like:
`This will usually be just "https://dev.azure.com"`?

**Comment by AlonAm** [comment]
I'm not sure the user should be able to change address, should he?

**Comment by finlaybob** [comment]
I would agree - as far as I know it's always the same. 

Maybe in very rare cases it's something different?
