### ISSUE TITLE
Azure Devops Pipelines - Using '$top=1' in API call will not return in progress builds

### ISSUE THREAD

**Issue by finlaybob** [AnyStatus/AnyStatus#44]
I had a build running and was not able to have this show up in the list. 

For some reason the URL having the $top parameter means it only returns completed builds. I could see the previous one, but not the one in progress currently.

If I pasted the API URL in browser - I get the same result - so it's not AnyStatus' doing. 

If I remove the $top=1 parameter - then I get the list as expected - with the inProgress build at the top. 

🤔

Maybe this is something on my Azure Org, will need to investigate a bit further when I get some time.

**Comment by AlonAm** [comment]
That's weird because I do get in-progress builds when connecting to our on-prem TFS. I'll give it a look when available
