### ISSUE TITLE
Azure DevOps WorkItems - Custom Query Support

### ISSUE THREAD

**Issue by f4n0** [AnyStatus/AnyStatus#46]
Hi,
I would like to support the Custom Query for listing the work items. 
As now, I've edited the code in this way, but I don't think that it is releasable as is:

file: `.\src\Plugins\AnyStatus.Plugins.Azure\WorkItems\AzureDevOpsWorkItemsWidget.cs`
```        
        [AsyncItemsSource(typeof(AzureDevOpsIterationSource), autoload: false)]
        public string Iteration { get; set; }

        [DisplayName("Custom Query")]
        public string CustomQuery { get; set; }
```

Here  I've edited a few things:

1. Added the CustomQuery Property
2. Removed the Required Attribute to the Iteration property

then in the file: `.\src\Plugins\AnyStatus.Plugins.Azure\WorkItems\AzureDevOpsWorkItemsQuery.cs`

```
 protected override async Task Handle(StatusRequest<AzureDevOpsWorkItemsWidget> request, CancellationToken cancellationToken)
        {
            var api = new AzureDevOpsApi(Endpoint);
            string wiql;

            if (string.IsNullOrEmpty(request.Context.CustomQuery))
            {
                wiql = string.Format(query, request.Context.Iteration);
            } else
            {
                wiql = request.Context.CustomQuery;
            }

           [the rest is the same]

```
In the Handle Task I've checked that if the customQuery has value then I will use that, otherwise, I will use the default one.

Hope this will help implements something!

BTW Thanks for the absolutely great work done!

here few screenshots:

![image](https://user-images.githubusercontent.com/36199751/139827806-31006549-c90c-4294-b7de-8da1987fd084.png)

![image](https://user-images.githubusercontent.com/36199751/139827839-7905bc71-3e8a-4b22-8162-cf20ca6817ba.png)

**Comment by AlonAm** [comment]
Hi @f4n0 
Thank you very much for investing the time to learn the API and contribute!

What is your opinion about adding a new widget specifically for this feature?

The existing widget will enable using predefined filters such as "Assign To", "Area Path, or "Iteration", without customizing the query. The new widget will enable specifying only a custom query without the other filters.

This way, the widgets are simplified and the users will have as little information on-screen as possible, and the code is kept simple.

At the moment, it's ok to duplicate the widget without sharing code between the new and existing widget. That can be refactored later.

What do you think?

**Comment by f4n0** [comment]
I think it could be great!
I don't know how it could be difficult to make something like that:

1. Write own query  on the go (with maybe some helpers/list of available tags) 
2. choose an existing query from DevOps (personal or shared) 

Thanks

**Comment by AlonAm** [comment]
It's a good idea to have both options, I don't think it should be too difficult. I'll give it a try

**Comment by AlonAm** [comment]
Here's the PR of the first widget: https://github.com/AnyStatus/AnyStatus/pull/47

**Comment by AlonAm** [comment]
Closing this issue for now as I have released a new version with improved support for custom queries.
If you still need a widget to view saved queries, please create a new issue / feature request
Thank you
