### ISSUE TITLE
UptimeRobot - An error occurred in [monitor name] Response status code does not indicate success: 404 (Not Found).

### ISSUE THREAD

**Issue by jimmy-rs** [AnyStatus/AnyStatus#52]
I have AnyStatus setup with some UptimeRobot health checks. They have been working for couple months. However, it stopped working about a week ago with error `An error occurred in [monitor name] Response status code does not indicate success: 404 (Not Found).` in Activity Log. At first I thought they had some down time. I've reach out to them and they said their API are working and I have confirmed by calling their API directly using the same api_key I used in AnyStatus and it worked. 

I was able to call their API at https://api.uptimerobot.com/v2/getMonitors using the same api_key without issue.

Question, how can I find out what the actual error is?

**Comment by AlonAm** [comment]
I suggest that we port the plugin to the new version and fix it there

**Comment by AlonAm** [comment]
I've started migrating the plugin to the new version of AnyStatus (v3).
The old plugin source code can be found here: https://github.com/AnyStatus/Plugins/blob/master/src/AnyStatus.Plugins/Widgets/HealthChecks/UptimeRobot/UptimeRobotCheck.cs

**Comment by AlonAm** [comment]
The UptimeRobot monitors widget has been ported to AnyStatus 3 which is available on Microsoft Store

![image](https://user-images.githubusercontent.com/3127610/145681193-5ad4925c-4174-4ab7-93f7-a707ed4d2a76.png)
